In [2]:
import numpy as np
import pandas as pd

In [12]:
titanic_df = pd.read_csv('titanic_train.csv')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)

df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame\n', df_list1)
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame\n', df_array1)

1차원 리스트로 만든 DataFrame
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame
    col1
0     1
1     2
2     3


In [4]:
col_name2 = ['col1', 'col2', 'col3']

list2= [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
array2 = np.array(list2)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('1차원 리스트로 만든 DataFrame\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('1차원 ndarray로 만든 DataFrame\n', df_array2)

1차원 리스트로 만든 DataFrame
    col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9
1차원 ndarray로 만든 DataFrame
    col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9


In [8]:
dict = { 'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33


In [10]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print(array3)

[[ 1  2  3]
 [11 22 33]]


In [11]:
list3 = df_dict.values.tolist()
dict3 = df_dict.to_dict()

print(list3)
print(dict3)

[[1, 2, 3], [11, 22, 33]]
{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}


In [13]:
titanic_df['Age_0'] = 0
print(titanic_df.head(3))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0  


In [15]:
titanic_df['Age_by_10'] = titanic_df['Age'] * 100
print(titanic_df.head(3))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      0     2200.0  
1      0          PC 17599  71.2833   C85        C      0     3800.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0     2600.0  


In [16]:
titanic_drop_df = titanic_df.drop('Age_0', axis=1, inplace=False)
titanic_drop_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_by_10  
0        0         A/5 21171   7.2500   NaN        S     2200.0  
1        0          PC 17599  71.2833   C85        C     3800.0  
2        0  STON/O2. 3101282   7.9250   NaN        S     2600.0  
3        0            113803  53.1000  C123        S     3500.0  
4        0            373450   8.0500   NaN        S     3500.0  
..     ...               ...      ...   ...      ...        ...  
886      0            211536  13.0000   NaN        S     2700.0  
887      0            112053  30.0000   B42        S     1900.0  
888      2        W./C. 6607  23.4500   NaN        S        NaN  
889      0            111369  30.0000  C148        C     2600.0  
890      0            370376   7.7500   NaN        Q     3200.0  

[891 rows x 13 columns]

In [17]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      0     2200.0  
1      0          PC 17599  71.2833   C85        C      0     3800.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0     2600.0

In [18]:
titanic_drop_df = titanic_df.drop(['Age_0', 'Age_by_10'], axis=1, inplace=True)

In [19]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [21]:
titanic_df.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [22]:
# Series의 index는 연산에서 제외. 오직 식별용으로 쓰임.
series_fair = titanic_df['Fare']
series_fair.head(5)

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [23]:
series_fair.max()

512.3292

In [24]:
series_fair.sum()

28693.9493

In [25]:
sum(series_fair)

28693.949299999967

In [26]:
(series_fair + 3).head(3)

0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

In [27]:
titanic_reset_df = titanic_df.reset_index(inplace=False)

In [28]:
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [29]:
titanic_reset_df.shape

(891, 13)